# Generated by Django 3.1.2 on 2020-12-07 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contribuintes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('responsavel', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caixa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('1', 'Dízimo'), ('2', 'Alçada'), ('3', 'Missionária'), ('4', 'Personalizada')], default='4', max_length=1)),
                ('responsavel', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LancamentoOferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(blank=True, max_length=500)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('info_adicional', models.TextField(blank=True, max_length=120)),
                ('contribuinte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribuinte', to='contribuintes.contribuinte')),
                ('lancar_no_caixa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tesouraria.caixa')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tesouraria.oferta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentooferta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DebitoNoCaixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(blank=True, max_length=500)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('date_saida', models.DateField(auto_now_add=True)),
                ('congregacao', models.CharField(max_length=120)),
                ('responsavel', models.CharField(max_length=120)),
                ('info_adicional', models.TextField(blank=True, max_length=120, null=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesouraria.caixa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debitonocaixa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_saida', 'valor'),
            },
        ),
        migrations.CreateModel(
            name='CreditoNoCaixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(blank=True, max_length=500)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('date_entrada', models.DateField(auto_now_add=True)),
                ('responsavel', models.CharField(max_length=120)),
                ('info_adicional', models.TextField(blank=True, max_length=120, null=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesouraria.caixa')),
                ('cxa_a_debitar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cxdebitar', to='tesouraria.caixa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditonocaixa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_entrada', 'valor'),
            },
        ),
    ]
