# Generated by Django 3.1.2 on 2020-12-07 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuinte',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pessoa')),
                ('classe', models.CharField(max_length=120)),
                ('contato', models.CharField(blank=True, max_length=120)),
                ('fidelidade', models.IntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribuinte', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.pessoa',),
        ),
    ]
